version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: sso_rabbit
    environment: 
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports: 
     - 5672:5672
     - 15672:15672
    restart: always
    networks:
      - netw_sso

networks:
  netw_sso:
    driver: bridge

